### ISSUE TITLE
Usage 1 example failes

### ISSUE THREAD

**Issue by timlinux** [catatnight/docker-postfix#3]
Referring to your first example:

```
sudo docker run -p 25:25 \
        -e maildomain=mail.example.com -e smtp_user=user:pwd \
        --name postfix -d catatnight/postfix
```

If I run that it fails with this in docker logs:

```
docker logs deployment_postfix_1
find: `/etc/postfix/certs': No such file or directory
find: `/etc/opendkim/domainkeys': No such file or directory
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.
For help, use /usr/bin/supervisord -h
```

Note I actually run it using this fig configuration:

```
postfix:
  image: catatnight/postfix
  hostname: postfix
  environment:
    # You could change this to something more suitable
    - maildomain=kartoza.com
    - smtp_user=noreply:docker
  volumes:
    - ./logs:/var/log

```
