### ISSUE TITLE
How to add second smtp user?

### ISSUE THREAD

**Issue by nalakawula** [catatnight/docker-postfix#33]
I want to have multiple smtp user, how to achive this?

**Comment by nalakawula** [comment]
Got it, I check your install.sh and get:
```
echo $smtp_user | tr , \\n > /tmp/passwd
while IFS=':' read -r _user _pwd; do
  echo $_pwd | saslpasswd2 -p -c -u $maildomain $_user
done < /tmp/passwd
chown postfix.sasl /etc/sasldb2
``` 
So to add second smtp user just add second user in smtp_user value. For example:
```
env:
        - name: maildomain
          value: "mydummydomain.com"
        - name: smtp_user
          value: "userone:mypass1,usertwo:mypass2"
```
